### ISSUE TITLE
ImportError: cannot import name 'Badge' from 'anybadge'

### ISSUE THREAD

**Issue by kagarlickij** [jongracecox/anybadge#42]
Hi there, I'm trying to use code snippet from README.md:
```
import anybadge

# Define thresholds: <2=red, <4=orange <8=yellow <10=green
thresholds = {2: 'red',
              4: 'orange',
              6: 'yellow',
              10: 'green'}

badge = anybadge.Badge('pylint', 2.22, thresholds=thresholds)

badge.write_badge('pylint.svg')
```

And getting `ImportError: cannot import name 'Badge' from 'anybadge' ` error.

Reproduced in both Python 2.7 and 3.7 environments, I used Docker:
```
FROM python:3.7
RUN apt-get update -y && \
    apt-get install nano -y && \
    pip install anybadge && \
    pip list
COPY . /opt
RUN python /opt/anybadge.py
```

..and `anybadge.py` with code above

**Comment by jongracecox** [comment]
I think your issue is that you have a file called `anybadge.py`, which means, in your code when you run `import anybadge` you are actually importing your `anybadge.py` file, and not the anybadge package.

You should be able to fix this by using a different filename (e.g. `run_anybadge.py`) and then using:

```dockerfile
FROM python:3.7
RUN apt-get update -y && \
    apt-get install nano -y && \
    pip install anybadge && \
    pip list
COPY . /opt
RUN python /opt/run_anybadge.py
```

**Comment by kagarlickij** [comment]
Many thanks @jongracecox I should have get another cup of coffee before naming)
